export const words = {
  rowOne: [
    'Javascript',
    'Python',
    'C++',
    'Go',
    'Kotlin',
    'C',
    'C#',
    'Java',
    'R',
    'SQL',
    'HTML/CSS',
    'Swift',
    'Ruby',
    'Dart',
    'Typescript',
    'React',
    'Angular',
    'Vue',
  ],
  rowTwo: [
    'Front End Development',
    'Back End Development',
    'Machine Learning',
    'Data Science',
    'Game Development',
    'Web Developer',
    'Mobile Development',
    'Full Stack Development',
    'Embedded Systems',
    'Software Engineer',
    'Cybersecurity',
  ],
};
